// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	// @gotags: validate:"required"
	// FirstName
	FirstName string `protobuf:"bytes,1,opt,name=FirstName" json:"FirstName,omitempty" validate:"required"`
	// @gotags: validate:"required"
	// LastName
	LastName string `protobuf:"bytes,2,opt,name=LastName" json:"LastName,omitempty" validate:"required"`
	// @gotags: validate:"gte=0,lte=130"
	// 年龄
	Age int32 `protobuf:"varint,3,opt,name=Age" json:"Age,omitempty" validate:"gte=0,lte=130"`
	// @gotags: validate:"required,email"
	Email string `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty" validate:"required,email"`
	// @gotags: validate:"iscolor"
	// alias for 'hexcolor|rgb|rgba|hsl|hsla'
	FavouriteColor       string   `protobuf:"bytes,5,opt,name=FavouriteColor" json:"FavouriteColor,omitempty" validate:"iscolor"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_42da8bae0055551d, []int{0}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetFavouriteColor() string {
	if m != nil {
		return m.FavouriteColor
	}
	return ""
}

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_42da8bae0055551d, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_42da8bae0055551d) }

var fileDescriptor_demo_42da8bae0055551d = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x73, 0x19, 0xb9, 0x04, 0x9d,
	0x8b, 0x52, 0x13, 0x4b, 0x52, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x64, 0xb8, 0x38, 0xdd, 0x32, 0x8b, 0x8a, 0x4b, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x52, 0x5c, 0x1c, 0x3e, 0x89, 0x50, 0x49, 0x26, 0xb0,
	0x24, 0x9c, 0x2f, 0x24, 0xc0, 0xc5, 0xec, 0x98, 0x9e, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1a,
	0x04, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0xba, 0xe6, 0x26, 0x66, 0xe6, 0x48, 0xb0, 0x80, 0x95, 0x42,
	0x38, 0x42, 0x6a, 0x5c, 0x7c, 0x6e, 0x89, 0x65, 0xf9, 0xa5, 0x45, 0x99, 0x25, 0xa9, 0xce, 0xf9,
	0x39, 0xf9, 0x45, 0x12, 0xac, 0x60, 0x69, 0x34, 0x51, 0x25, 0x03, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xfc, 0x14, 0x98, 0x83, 0xc0, 0x6c,
	0x90, 0x7d, 0xb9, 0xc5, 0xe9, 0x50, 0x67, 0x80, 0x98, 0x49, 0x6c, 0x60, 0x8f, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x2c, 0x08, 0x29, 0xed, 0x00, 0x00, 0x00,
}
