// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: request.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEdgeServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: validate:"required"
	RequestId string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty" validate:"required"`
	// @gotags: validate:"required,public"
	// [optional] <<<公共请求参数>>> 私有云忽略，适配腾讯云API规范
	AppId int64 `protobuf:"varint,2,opt,name=AppId,proto3" json:"AppId,omitempty" validate:"required,public"`
	// @gotags: validate:"required,public"
	// [optional] <<<公共请求参数>>> 私有云忽略，适配腾讯云API规范
	Region string `protobuf:"bytes,3,opt,name=Region,proto3" json:"Region,omitempty" validate:"required,public"`
	// [optional] <<<公共请求参数>>> 私有云忽略，适配腾讯云API规范
	// @gotags: validate:"required,public"
	Action string `protobuf:"bytes,4,opt,name=Action,proto3" json:"Action,omitempty" validate:"required,public"`
	// @gotags: validate:"required,public"
	// [required] <<<公共请求参数>>> 用户 uin, 网关自动设置
	Uin string `protobuf:"bytes,5,opt,name=Uin,proto3" json:"Uin,omitempty" validate:"required,public"`
	// @gotags: validate:"required,public"
	// [optional] <<<公共请求参数>>> 私有云忽略，适配腾讯云API规范
	SubAccountUin string `protobuf:"bytes,6,opt,name=SubAccountUin,proto3" json:"SubAccountUin,omitempty" validate:"required,public"`
	// @gotags: validate:"required,public"
	// [optional] <<<公共请求参数>>> 私有云忽略，适配腾讯云API规范
	Version string `protobuf:"bytes,7,opt,name=Version,proto3" json:"Version,omitempty" validate:"required,public"`
	// @gotags: validate:"required"
	// 语言选项: zh-CN; en-US
	Language string `protobuf:"bytes,8,opt,name=Language,proto3" json:"Language,omitempty" validate:"required"`
	// @gotags: validate:"required,gt=0,dive,required"
	// [required] 边缘单元信息
	EdgeUnits []*EdgeUnit `protobuf:"bytes,10,rep,name=EdgeUnits,proto3" json:"EdgeUnits,omitempty" validate:"required,gt=0,dive,required"`
	// @gotags: validate:"required"
	ServiceGroupId string `protobuf:"bytes,12,opt,name=ServiceGroupId,proto3" json:"ServiceGroupId,omitempty" validate:"required"`
	// @gotags: validate:"required"
	// [required] 服务类别名称
	ServiceGroupName string `protobuf:"bytes,13,opt,name=ServiceGroupName,proto3" json:"ServiceGroupName,omitempty" validate:"required"`
	// @gotags: validate:"required,max=500"
	// [optional] 在线推理服务描述
	ServiceDescription string `protobuf:"bytes,14,opt,name=ServiceDescription,proto3" json:"ServiceDescription,omitempty" validate:"required,max=500"`
	// @gotags: validate:"required"
	// [required] 在线推理服务对应的模型服务配置Id
	ServiceConfigId string `protobuf:"bytes,15,opt,name=ServiceConfigId,proto3" json:"ServiceConfigId,omitempty" validate:"required"`
	// @gotags: validate:"min=0"
	// [optional] 兼容旧协议，业务ID，以TiBusinessId代替
	BusinessId string `protobuf:"bytes,16,opt,name=BusinessId,proto3" json:"BusinessId,omitempty" validate:"min=0"`
	// @gotags: validate:"min=0"
	// [optional] 兼容旧协议，项目ID，以TiProjectId代替
	AppGroupId string `protobuf:"bytes,17,opt,name=AppGroupId,proto3" json:"AppGroupId,omitempty" validate:"min=0"`
	// @gotags: validate:""
	// [optional] 工作负载(Workload)类型，可选：["deployment", "statefulset"]，不填默认deployment
	WorkloadType string `protobuf:"bytes,18,opt,name=WorkloadType,proto3" json:"WorkloadType,omitempty"`
	// @gotags: validate:"required"
	// [required] 是否是灰度更新
	CanaryUpdate bool `protobuf:"varint,23,opt,name=CanaryUpdate,proto3" json:"CanaryUpdate,omitempty" validate:"required"`
	// @gotags: validate:"required, gt=0"
	// [required] 项目Id
	TiProjectId int64 `protobuf:"varint,24,opt,name=TiProjectId,proto3" json:"TiProjectId,omitempty" validate:"required, gt=0"`
	// @gotags: validate:"required, gt=0"
	// [required] 业务Id
	TiBusinessId int64 `protobuf:"varint,25,opt,name=TiBusinessId,proto3" json:"TiBusinessId,omitempty" validate:"required, gt=0"`
	// @gotags: validate:"required"
	// [optional] 服务类型。服务类型(platform_service:平台服务, user_service:用户服务)
	ServiceType string `protobuf:"bytes,26,opt,name=ServiceType,proto3" json:"ServiceType,omitempty" validate:"required"`
}

func (x *CreateEdgeServiceRequest) Reset() {
	*x = CreateEdgeServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEdgeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeServiceRequest) ProtoMessage() {}

func (x *CreateEdgeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeServiceRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEdgeServiceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CreateEdgeServiceRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetUin() string {
	if x != nil {
		return x.Uin
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetSubAccountUin() string {
	if x != nil {
		return x.SubAccountUin
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetEdgeUnits() []*EdgeUnit {
	if x != nil {
		return x.EdgeUnits
	}
	return nil
}

func (x *CreateEdgeServiceRequest) GetServiceGroupId() string {
	if x != nil {
		return x.ServiceGroupId
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetServiceGroupName() string {
	if x != nil {
		return x.ServiceGroupName
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetServiceDescription() string {
	if x != nil {
		return x.ServiceDescription
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetServiceConfigId() string {
	if x != nil {
		return x.ServiceConfigId
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetAppGroupId() string {
	if x != nil {
		return x.AppGroupId
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

func (x *CreateEdgeServiceRequest) GetCanaryUpdate() bool {
	if x != nil {
		return x.CanaryUpdate
	}
	return false
}

func (x *CreateEdgeServiceRequest) GetTiProjectId() int64 {
	if x != nil {
		return x.TiProjectId
	}
	return 0
}

func (x *CreateEdgeServiceRequest) GetTiBusinessId() int64 {
	if x != nil {
		return x.TiBusinessId
	}
	return 0
}

func (x *CreateEdgeServiceRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

type EdgeUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: validate:"required"
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" validate:"required"`
	// @gotags: validate:"required"
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" validate:"required"`
	// @gotags: validate:"required"
	NodeGroup string `protobuf:"bytes,3,opt,name=NodeGroup,proto3" json:"NodeGroup,omitempty" validate:"required"`
}

func (x *EdgeUnit) Reset() {
	*x = EdgeUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeUnit) ProtoMessage() {}

func (x *EdgeUnit) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeUnit.ProtoReflect.Descriptor instead.
func (*EdgeUnit) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeUnit) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EdgeUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EdgeUnit) GetNodeGroup() string {
	if x != nil {
		return x.NodeGroup
	}
	return ""
}

var File_request_proto protoreflect.FileDescriptor

var file_request_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x05, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x75, 0x62,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x53, 0x75, 0x62, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x69, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x45, 0x64, 0x67, 0x65, 0x55, 0x6e, 0x69,
	0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x64, 0x67, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x09, 0x45, 0x64, 0x67, 0x65, 0x55,
	0x6e, 0x69, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x64,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x70, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x61, 0x72, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x17, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x43, 0x61,
	0x6e, 0x61, 0x72, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x69,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x18, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x54, 0x69, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x54, 0x69, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x64, 0x18, 0x19, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x54, 0x69, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x1a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x4c, 0x0a, 0x08, 0x45, 0x64, 0x67, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_request_proto_rawDescOnce sync.Once
	file_request_proto_rawDescData = file_request_proto_rawDesc
)

func file_request_proto_rawDescGZIP() []byte {
	file_request_proto_rawDescOnce.Do(func() {
		file_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_request_proto_rawDescData)
	})
	return file_request_proto_rawDescData
}

var file_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_request_proto_goTypes = []interface{}{
	(*CreateEdgeServiceRequest)(nil), // 0: proto.CreateEdgeServiceRequest
	(*EdgeUnit)(nil),                 // 1: proto.EdgeUnit
}
var file_request_proto_depIdxs = []int32{
	1, // 0: proto.CreateEdgeServiceRequest.EdgeUnits:type_name -> proto.EdgeUnit
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_proto_init() }
func file_request_proto_init() {
	if File_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEdgeServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_goTypes,
		DependencyIndexes: file_request_proto_depIdxs,
		MessageInfos:      file_request_proto_msgTypes,
	}.Build()
	File_request_proto = out.File
	file_request_proto_rawDesc = nil
	file_request_proto_goTypes = nil
	file_request_proto_depIdxs = nil
}
